# Site settings
title: Carldmitch
email: carldmitch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The next best thing to winning 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carldmitch.github.io" # the base hostname & protocol for your site
twitter_username: carldmitch
github_username:  carldmitch
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
# Collections
collections:
  musics:
    output: true
  albums:
    output: true
  playlists:
    output: true
